# 模型参数
model:
  num_classes: 20
  pretrained_model: "google/vit-base-patch16-224"
  image_size: 640

# 训练参数
train:
  epochs: 1000
  batch: 16
  lr0: 0.01
  momentum: 0.937
  weight_decay: 0.0005
  patience: 100
  save: true
  save_period: 10
  device: 0

# 数据增强
augment:
  enabled: true
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  flipud: 0.5
  fliplr: 0.5
  mosaic: 1.0
  mixup: 0.2
  scale: 0.5
  perspective: 0.001
  shear: 0.001
  translate: 0.1

# 数据集配置
data:
  train: "path/to/train.txt"
  val: "path/to/val.txt"
  test: "path/to/test.txt"
  nc: 20  # 类别数量
  names: ["class1", "class2", "..."]  # 类别名称 